baseURL = "/"
languageCode = "en-us"
title = "SharingApples"
theme = "main-road"
pygmentsCodeFences = true
[Params]
  toc = true
  post_navigation = true
  post_meta = ["date"]
  readmore = false

[Params.sidebar]
  home = "right"
  list = "right"
  single = true
  widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets.social]
  github = "sharingapples"
